function P = protocol_HN()
% PROTOCOL_HN  Head-and-Neck protocol for FSIRO.
%
% dT (target reference dose) and Dp (prescription) are read automatically from
% the .mat file, so they are NOT set here. To force values, add fields P.dT /
% P.Dp. To add a new site, copy this file and edit the entries below; FSIRO
% is protocol-agnostic and locates every structure by name.

    P.name   = 'Head-and-Neck';
    P.mu_min = 0.2;     % surprise smoothing threshold

    % Target: bilateral membership, fractions of dT.
    P.target.pattern = '^PTV';
    P.target.exclude = 'Shell';   % avoid matching "PTV Shell ..."
    P.target.lo      = 0.9048;    % lower support
    P.target.core_lo = 0.941;     % plateau start (trapezoidal)
    P.target.core_hi = 0.966;     % plateau end   (trapezoidal)
    P.target.peak    = 1.000;     % peak          (triangular)
    P.target.hi      = 1.019;     % upper support

    % OARs: left-anchored membership. 'goal' is the plateau end (trapezoidal);
    % 'support' (bE) must sit above the achievable dose; 'type' selects the
    % evaluation metric (serial -> Dmax, parallel -> Dmean); 'eval_limit' (Gy)
    % is the clinical (QUANTEC) limit used only in evaluation. Goals/supports/
    % limits are clinical modelling choices and can be tuned.
    o = @(pat,g,sup,ty,evlim) struct('pattern',pat,'goal',g,'support',sup, ...
                                     'type',ty,'eval_limit',evlim);
    P.oars = [ ...
        o('^Spinal Cord',  30,  50,  'serial',   50), ...
        o('^Brainstem',    30,  54,  'serial',   54), ...
        o('^Larynx',       34.5,48.3,'parallel', 44), ...
        o('^Parotid \(R\)',26,  50,  'parallel', 25), ...
        o('^Parotid \(L\)',26,  50,  'parallel', 25), ...
        o('^SMG \(R\)',    35,  50,  'parallel', 39), ...
        o('^SMG \(L\)',    35,  50,  'parallel', 39), ...
        o('^Oral Cavity',  35,  60,  'parallel', 40), ...
        o('^Cochlea \(R\)',45,  55,  'parallel', 45), ...
        o('^Cochlea \(L\)',45,  55,  'parallel', 45), ...
        o('^MCS',          50,  65,  'parallel', 50), ...
        o('^MCM',          50,  65,  'parallel', 50), ...
        o('^MCI',          50,  65,  'parallel', 50), ...
        o('^MCP',          50,  65,  'parallel', 50), ...
        o('^Oesophagus',   35,  60,  'parallel', 34) ];
end